server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: smart-campus
  
  # 数据库配置 - 使用H2内存数据库便于开发测试
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:smartcampus;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  
  # H2数据库控制台
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Web相关配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.smartcampus.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# 日志配置
logging:
  level:
    root: info
    com.smartcampus: debug

# JWT配置
jwt:
  secret: your-secret-key-here-should-be-very-long-and-secure-in-production
  expiration: 86400000  # 24小时

# 系统参数配置
system:
  # 文件上传路径
  file-upload-path: upload/
  # 允许的文件类型
  allowed-file-types: jpg,jpeg,png,gif,doc,docx,xls,xlsx,pdf,zip,rar
  # 最大文件大小 (10MB)
  max-file-size: 10485760 