# Development Environment Configuration

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartcampus?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  # JPA / Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# Logging Configuration
logging:
  level:
    root: INFO
    com:
      smartcampus: DEBUG
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# Application-specific settings
app:
  notification:
    test-mode: true 