package com.smartcampus.common.response;

import lombok.Getter;

/**
 * Standard API Result Codes
 */
@Getter // Lombok annotation to generate getters
public enum ResultCode {

    SUCCESS(200, "Success"),
    FAILURE(500, "Failure"), // Generic failure

    // Client Errors (4xx)
    BAD_REQUEST(400, "Bad Request"),
    UNAUTHORIZED(401, "Unauthorized"),
    FORBIDDEN(403, "Forbidden"),
    NOT_FOUND(404, "Not Found"),
    METHOD_NOT_ALLOWED(405, "Method Not Allowed"),
    CONFLICT(409, "Conflict"), // e.g., duplicate entry
    UNPROCESSABLE_ENTITY(422, "Unprocessable Entity"), // Validation errors

    // Server Errors (5xx)
    INTERNAL_SERVER_ERROR(500, "Internal Server Error"),
    SERVICE_UNAVAILABLE(503, "Service Unavailable"),

    // Business Specific Errors (Optional: Define ranges like 1xxxx, 2xxxx)
    LOGIN_ERROR(10001, "Login Error: Invalid Credentials"),
    USER_NOT_FOUND(10002, "User Not Found"),
    ROLE_NOT_FOUND(10003, "Role Not Found"),
    PERMISSION_DENIED(10004, "Permission Denied");


    private final int code;
    private final String message;

    ResultCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

    // Getters are generated by Lombok's @Getter
} 